# Generated by Django 4.2.11 on 2024-11-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=80)),
                ('learning_obj', models.CharField(max_length=40)),
                ('course_contents', models.CharField(max_length=1000)),
                ('teaching_methods', models.CharField(max_length=40)),
                ('prerequisites', models.CharField(max_length=40)),
                ('reading', models.CharField(max_length=40)),
                ('applicability', models.CharField(max_length=80)),
                ('workload', models.CharField(max_length=40)),
                ('credits', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('evaluation', models.CharField(max_length=40)),
                ('term', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=40)),
                ('course_type', models.CharField(max_length=400)),
                ('medium_of_instruction', models.CharField(max_length=40)),
            ],
        ),
    ]
