# Generated by Django 4.2.11 on 2024-11-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeCourse',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=80)),
                ('learning_obj', models.CharField(max_length=40)),
                ('course_contents', models.CharField(max_length=1000)),
                ('teaching_methods', models.CharField(max_length=40)),
                ('prerequisites', models.CharField(max_length=40)),
                ('reading', models.CharField(max_length=40)),
                ('applicability', models.CharField(max_length=80)),
                ('workload', models.CharField(max_length=40)),
                ('credits', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('evaluation', models.CharField(max_length=40)),
                ('term', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=40)),
                ('course_type', models.CharField(max_length=400)),
                ('medium_of_instruction', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'merge_course',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
