# Generated by Django 4.2.11 on 2024-11-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0002_mergecourse_delete_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mergecourse',
            table='merged_course',
        ),
    ]
