# Generated by Django 4.2.11 on 2024-11-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0003_alter_mergecourse_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mergecourse',
            table='merged_courses',
        ),
    ]
