# Generated by Django 4.2.16 on 2024-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0005_courseera'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEra2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('course_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course_url', models.URLField()),
                ('course_description', models.TextField()),
                ('skills', models.TextField()),
            ],
            options={
                'db_table': 'course_era',
            },
        ),
        migrations.DeleteModel(
            name='CourseEra',
        ),
    ]
