# Generated by Django 4.2.16 on 2024-11-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0006_courseera2_delete_courseera'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseera2',
            table='course_era22',
        ),
    ]
