# Generated by Django 4.2.16 on 2024-11-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0007_alter_courseera2_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseera2',
            table='course_era2',
        ),
    ]
