# Generated by Django 4.1.7 on 2024-11-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0008_alter_courseera2_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseEra2',
        ),
    ]
