# Generated by Django 4.1.7 on 2024-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0009_delete_courseera2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEra2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=255)),
                ('University', models.CharField(max_length=255)),
                ('Difficulty_Level', models.CharField(max_length=50)),
                ('Course_Rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Course_URL', models.URLField()),
                ('Course_Description', models.TextField()),
                ('Skills', models.TextField()),
            ],
            options={
                'db_table': 'coursera_2',
                'managed': False,
            },
        ),
    ]
