# Generated by Django 4.2.11 on 2024-12-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0010_courseera2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Term', models.CharField(max_length=255)),
                ('YearTerm', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Number', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Credit_Hours', models.CharField(max_length=255)),
                ('Section_Info', models.CharField(max_length=255)),
                ('Degree_Attributes', models.CharField(max_length=255)),
                ('Schedule_Information', models.CharField(max_length=255)),
                ('CRN', models.IntegerField()),
                ('Section', models.IntegerField()),
                ('Status_Code', models.CharField(max_length=255)),
                ('Part_Of_Term', models.IntegerField()),
                ('Section_Title', models.IntegerField()),
                ('Section_Credit_Hours', models.IntegerField()),
                ('Section_Status', models.CharField(max_length=255)),
                ('Enrollment_Status', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Type_Code', models.CharField(max_length=255)),
                ('Start_time', models.DateTimeField(max_length=255)),
                ('End_Time', models.DateTimeField(max_length=255)),
                ('Days_of_Week', models.CharField(max_length=255)),
                ('Room', models.CharField(max_length=255)),
                ('Building', models.CharField(max_length=255)),
                ('Instructors', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course-catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coursera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('price', models.CharField(max_length=255)),
                ('course_by', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviews', models.CharField(max_length=255)),
                ('level_type_duration', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'coursera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseTitle', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Availability', models.CharField(max_length=255)),
                ('Cost', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CoursesData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('University', models.CharField(max_length=255)),
                ('Difficulty_Level', models.CharField(max_length=255)),
                ('Link', models.URLField()),
                ('About', models.TextField()),
                ('Course_Description', models.TextField()),
            ],
            options={
                'db_table': 'EdX',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Udemy_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('is_paid', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('num_subscribers', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('content_duration', models.DecimalField(decimal_places=1, max_digits=3)),
                ('published_timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'udemy_courses',
                'managed': False,
            },
        ),
    ]
