# Generated by Django 4.2.11 on 2024-12-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0011_coursecatalog_coursera_coursesdata_edx_udemy_courses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecatalog',
            table='course_catalog',
        ),
        migrations.AlterModelTable(
            name='coursera',
            table='maincourse',
        ),
    ]
