# Generated by Django 4.2.11 on 2024-12-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0012_alter_coursecatalog_table_alter_coursera_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecatalog',
            table='course_catalog_1_',
        ),
        migrations.AlterModelTable(
            name='courseera2',
            table='coursera_2_',
        ),
        migrations.AlterModelTable(
            name='coursera',
            table='maincourse_',
        ),
        migrations.AlterModelTable(
            name='edx',
            table='edx_',
        ),
        migrations.AlterModelTable(
            name='udemy_courses',
            table='udemy_courses_',
        ),
    ]
