# Generated by Django 4.2.11 on 2024-12-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0013_alter_coursecatalog_table_alter_courseera2_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesdata',
            options={},
        ),
    ]
