# Generated by Django 4.2.11 on 2024-12-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0014_alter_coursesdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesdata',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='coursecatalog',
            table='course_catalog_2_',
        ),
        migrations.AlterModelTable(
            name='courseera2',
            table='coursera_2_2_',
        ),
        migrations.AlterModelTable(
            name='coursera',
            table='maincourse_2_',
        ),
        migrations.AlterModelTable(
            name='edx',
            table='edx_1_',
        ),
    ]
