# Generated by Django 4.2.11 on 2024-12-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0015_alter_coursesdata_options_alter_coursecatalog_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseera2',
            table='coursera_2__2_',
        ),
        migrations.AlterModelTable(
            name='coursesdata',
            table='coursesdata_2_',
        ),
    ]
