# Generated by Django 4.2.11 on 2024-12-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0016_alter_courseera2_table_alter_coursesdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecatalog',
            table='course_catalog__2_',
        ),
    ]
