# Generated by Django 4.2.11 on 2024-12-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0017_alter_coursecatalog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursera',
            table='maincourse__2_',
        ),
    ]
