# Generated by Django 4.2.11 on 2024-12-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0018_alter_coursera_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursesdata',
            table='coursesdata__2_',
        ),
        migrations.AlterModelTable(
            name='edx',
            table='edx__1_',
        ),
    ]
