# Generated by Django 4.2.11 on 2024-12-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0019_alter_coursesdata_table_alter_edx_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursesdata',
            table='coursesdata__1_',
        ),
    ]
